/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

val COMPANY_NAME = "OnlyCoiners"

fun main() {
    reuse(COMPANY_NAME)
    println(App().greeting)
}
