/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

val ONE_SECOND = 1000L

fun reuse(name: String) {
  println("Hello world from $name")
  Thread.sleep(ONE_SECOND)
  println("End")
}
